 /* eslint-disable */

/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var x$cite_io_protos_model_tracking_pb = require('../../../x-cite.io/protos/model/tracking_pb.js');
goog.object.extend(proto, x$cite_io_protos_model_tracking_pb);
var x$cite_io_protos_model_basic_pb = require('../../../x-cite.io/protos/model/basic_pb.js');
goog.object.extend(proto, x$cite_io_protos_model_basic_pb);
goog.exportSymbol('proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest', null, global);
goog.exportSymbol('proto.xcite.iot.trackingsubscriber.v1.ReportList', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest.repeatedFields_, null);
};
goog.inherits(proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest.displayName = 'proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xcite.iot.trackingsubscriber.v1.ReportList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.xcite.iot.trackingsubscriber.v1.ReportList.repeatedFields_, null);
};
goog.inherits(proto.xcite.iot.trackingsubscriber.v1.ReportList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.xcite.iot.trackingsubscriber.v1.ReportList.displayName = 'proto.xcite.iot.trackingsubscriber.v1.ReportList';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest.toObject = function(includeInstance, msg) {
  var obj = {
    idList: jspb.Message.toObjectList(msg.getIdList(),
    x$cite_io_protos_model_basic_pb.UUID.toObject, includeInstance),
    reportInterval: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest}
 */
proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest;
  return proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest}
 */
proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new x$cite_io_protos_model_basic_pb.UUID;
      reader.readMessage(value,x$cite_io_protos_model_basic_pb.UUID.deserializeBinaryFromReader);
      msg.addId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setReportInterval(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      x$cite_io_protos_model_basic_pb.UUID.serializeBinaryToWriter
    );
  }
  f = message.getReportInterval();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * repeated xcite.iot.model.v1.UUID id = 1;
 * @return {!Array<!proto.xcite.iot.model.v1.UUID>}
 */
proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest.prototype.getIdList = function() {
  return /** @type{!Array<!proto.xcite.iot.model.v1.UUID>} */ (
    jspb.Message.getRepeatedWrapperField(this, x$cite_io_protos_model_basic_pb.UUID, 1));
};


/** @param {!Array<!proto.xcite.iot.model.v1.UUID>} value */
proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest.prototype.setIdList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.xcite.iot.model.v1.UUID=} opt_value
 * @param {number=} opt_index
 * @return {!proto.xcite.iot.model.v1.UUID}
 */
proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest.prototype.addId = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.xcite.iot.model.v1.UUID, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest.prototype.clearIdList = function() {
  this.setIdList([]);
};


/**
 * optional int32 report_interval = 2;
 * @return {number}
 */
proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest.prototype.getReportInterval = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.xcite.iot.trackingsubscriber.v1.GetReportStreamRequest.prototype.setReportInterval = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.xcite.iot.trackingsubscriber.v1.ReportList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xcite.iot.trackingsubscriber.v1.ReportList.prototype.toObject = function(opt_includeInstance) {
  return proto.xcite.iot.trackingsubscriber.v1.ReportList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xcite.iot.trackingsubscriber.v1.ReportList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xcite.iot.trackingsubscriber.v1.ReportList.toObject = function(includeInstance, msg) {
  var obj = {
    reportListList: jspb.Message.toObjectList(msg.getReportListList(),
    x$cite_io_protos_model_tracking_pb.TrackerReport.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xcite.iot.trackingsubscriber.v1.ReportList}
 */
proto.xcite.iot.trackingsubscriber.v1.ReportList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xcite.iot.trackingsubscriber.v1.ReportList;
  return proto.xcite.iot.trackingsubscriber.v1.ReportList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xcite.iot.trackingsubscriber.v1.ReportList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xcite.iot.trackingsubscriber.v1.ReportList}
 */
proto.xcite.iot.trackingsubscriber.v1.ReportList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new x$cite_io_protos_model_tracking_pb.TrackerReport;
      reader.readMessage(value,x$cite_io_protos_model_tracking_pb.TrackerReport.deserializeBinaryFromReader);
      msg.addReportList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xcite.iot.trackingsubscriber.v1.ReportList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xcite.iot.trackingsubscriber.v1.ReportList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xcite.iot.trackingsubscriber.v1.ReportList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xcite.iot.trackingsubscriber.v1.ReportList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReportListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      x$cite_io_protos_model_tracking_pb.TrackerReport.serializeBinaryToWriter
    );
  }
};


/**
 * repeated xcite.iot.model.v1.TrackerReport report_list = 1;
 * @return {!Array<!proto.xcite.iot.model.v1.TrackerReport>}
 */
proto.xcite.iot.trackingsubscriber.v1.ReportList.prototype.getReportListList = function() {
  return /** @type{!Array<!proto.xcite.iot.model.v1.TrackerReport>} */ (
    jspb.Message.getRepeatedWrapperField(this, x$cite_io_protos_model_tracking_pb.TrackerReport, 1));
};


/** @param {!Array<!proto.xcite.iot.model.v1.TrackerReport>} value */
proto.xcite.iot.trackingsubscriber.v1.ReportList.prototype.setReportListList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.xcite.iot.model.v1.TrackerReport=} opt_value
 * @param {number=} opt_index
 * @return {!proto.xcite.iot.model.v1.TrackerReport}
 */
proto.xcite.iot.trackingsubscriber.v1.ReportList.prototype.addReportList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.xcite.iot.model.v1.TrackerReport, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.xcite.iot.trackingsubscriber.v1.ReportList.prototype.clearReportListList = function() {
  this.setReportListList([]);
};


goog.object.extend(exports, proto.xcite.iot.trackingsubscriber.v1);
